<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title><g:message code="user.title"/></title>
    <r:require modules="jquery"/>
</head>

<body>
<div class="breadcrumbs">
    <a class="small-link" href="../"><g:message code="user.title"/></a> > <g:message code="user.details.title"/>
</div>

<div class="refresh-btn">
    <a onclick="refreshUserReport(${user.id})"><g:message code="generic.refresh"/></a>
</div>
<h1>${user.name}</h1>

<ul id="report-list" class="report-list">
    <!-- Content is generated by client -->
</ul>

</body>

<r:script>
// In real word application, we'll certainly want this script somewhere else!

// Refresh report name lists
function refreshUserReport(userId) {
    $.ajax({
        url:"${g.createLink(controller:'user',action:'getReports')}",
        data: {id: userId},
        success: function(reports) {
            var ul = $('#report-list')
            // Remove all elements
            ul.empty()
            // Refill it...
            for (var i = 0; i < reports.length; i++) {
                var report = reports[i]
                ul.append('<li class="report"><span class="report-name">' + report.name + '</span></li>')
            }
        }
    })
}

// Initial loading...
refreshUserReport(${user.id})
</r:script>
</html>